version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bookstoredb
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080